apiVersion: skaffold/v2beta28
kind: Config
build:
  tagPolicy:
    sha256: {}
  # defines where to find the code at build time and where to push the resulting image
  artifacts:
  - image: area-controller
    context: app/api/Docker/area
    sync:
      infer:
      - '**/*'
  - image: registration-controller
    context: app/api/Docker/registration
    sync:
      infer:
      - '**/*'
  - image: validation-controller
    context: app/api/Docker/validation
    sync:
      infer:
        - '**/*'
  - image: application
    context: app
    sync:
      infer:
        - '**/*'
profiles:
# use the cloudbuild profile to build images using Google Cloud Build
- name: cloudbuild
  build:
    googleCloudBuild: {}
    artifacts:
    - image: area-controller
      context: app/api/Docker/area
      sync:
        infer:
          - '**/*'
      kaniko:
        cache: {}
    - image: registration-controller
      context: app/api/Docker/registration
      sync:
        infer:
          - '**/*'
      kaniko:
        cache: {}
    - image: validation-controller
      context: app/api/Docker/validation
      sync:
        infer:
          - '**/*'
      kaniko:
        cache: { }
    - image: application
      context: app
      sync:
        infer:
          - '**/*'
      kaniko:
        cache: { }